development: &defaults
#  connection:
  access_key_id: AKIAIRAKQIZVMOVIPVHQ
  secret_access_key: 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
  persistent: true
  bucket: comilffo
  max_file_size: 10485760
  acl: public-read

test:
  <<: *defaults
  bucket: comilffo

staging:
  <<: *defaults
  bucket: comilffo

production:
  <<: *defaults
  # prefix is optional. This is where you would put your CloudFront Domain
  # Name or your CloudFront CNAME if you have one configured.
  prefix: "http://project.s3.mydomain.com"
  bucket: comilffo